# Generated by Django 6.0.4 on 2026-04-23 06:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
