# Generated by Django 6.0.4 on 2026-04-23 08:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_track_cover_image_track_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='mix',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
